// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "luke-voice",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "luke-voice",
            targets: ["AppModule"],
            bundleIdentifier: "br.valenca.lucas.luke-voice",
            teamIdentifier: "9FWLTGWA8V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .moon),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "aaaaa")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/AudioKit/AudioKit.git", "5.0.0"..<"6.0.0"),
        .package(url: "https://github.com/AudioKit/AudioKitUI.git", "0.3.5"..<"1.0.0"),
        .package(url: "https://github.com/AudioKit/AudioKitEX.git", "5.0.0"..<"6.0.0"),
        .package(url: "https://github.com/AudioKit/SoundpipeAudioKit.git", "5.0.0"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "AudioKit", package: "audiokit"),
                .product(name: "AudioKitUI", package: "audiokitui"),
                .product(name: "AudioKitEX", package: "audiokitex"),
                .product(name: "SoundpipeAudioKit", package: "soundpipeaudiokit")
            ],
            path: "."
        )
    ]
)